spring.application.name=chatbot-anticipos-iti

# Configuración del servidor
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_anticipos_iti
spring.datasource.username=postgres
spring.datasource.password=515l3m4k3ll
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Logging
logging.level.org.springframework=INFO